image: registry.tccenter.ru/public/golang:1.17.7-buster

stages:
  - test
  - build
  - upload
  - release

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - mkdir -p binaries
    - |
      platforms=("windows/amd64" "windows/386" "darwin/amd64" "darwin/arm64" "linux/amd64" "linux/386" "linux/arm64")

      for platform in "${platforms[@]}"
      do
      	platform_split=(${platform//\// })
      	GOOS=${platform_split[0]}
      	GOARCH=${platform_split[1]}
      	output_name=bctl'-'$GOOS'-'$GOARCH'-'$CI_COMMIT_TAG
      	if [ $GOOS = "windows" ]; then
      		output_name+='.exe'
      	fi	

      	env GOOS=$GOOS GOARCH=$GOARCH go build -o binaries/$output_name
      	if [ $? -ne 0 ]; then
         		echo 'An error has occurred! Aborting the script execution...'
      		exit 1
      	fi
      done
  artifacts:
    paths:
      - binaries
    expire_in: 1 yrs
  only:
    - tags

upload:
  stage: upload
  script:
    - |
        platforms=("windows/amd64" "windows/386" "darwin/amd64" "darwin/arm64" "linux/amd64" "linux/386" "linux/arm64")

        for platform in "${platforms[@]}"
        do
        	platform_split=(${platform//\// })
        	GOOS=${platform_split[0]}
        	GOARCH=${platform_split[1]}
        	output_name=bctl'-'$GOOS'-'$GOARCH'-'$CI_COMMIT_TAG
        	if [ $GOOS = "windows" ]; then
        		output_name+='.exe'
        	fi	
            curl -v --user "$SERVICE_USER:$SERVICE_PASSWORD" --upload-file binaries/$output_name https://nexus.tccenter.ru/repository/irsd/bctl/$CI_COMMIT_TAG/$output_name
        done
  artifacts:
    paths:
      - binaries
    expire_in: 1 yrs
  only:
    - tags

release:
  stage: release
  script:
    - |
        platforms=("windows/amd64" "windows/386" "darwin/amd64" "darwin/arm64" "linux/amd64" "linux/386" "linux/arm64")
        DESCRIPTION='All assets for release $CI_COMMIT_TAG'
        ASSETS=''
        for platform in "${platforms[@]}"
        do
            platform_split=(${platform//\// })
            GOOS=${platform_split[0]}
            GOARCH=${platform_split[1]}
            output_name=bctl'-'$GOOS'-'$GOARCH'-'$CI_COMMIT_TAG
            if [ $GOOS = "windows" ]; then
            output_name+='.exe'
            fi	
            ASSETS="${ASSETS}{ \"name\": \"$output_name\", \"url\": \"https://nexus.tccenter.ru/repository/irsd/bctl/$CI_COMMIT_TAG/$output_name\", \"link_type\":\"package\" }"
            if [ $counter -lt ${#platforms[@]} ]
            then
                ASSETS="${ASSETS},"
            else
                ASSETS="${ASSETS}"
            fi
            (( counter = counter + 1 ))
        done
        curl --request POST --header 'Content-Type: application/json' --header "Private-Token: $ACCESS_TOKEN" --data "{\"name\": \"Release $CI_COMMIT_TAG\", \"tag_name\": \"$CI_COMMIT_TAG\", \"description\": \"$DESCRIPTION\", \"assets\": { \"links\": [$ASSETS] }}" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases"
  only:
    - tags
